### ISSUE TITLE
Event Information

### ISSUE THREAD

**Issue by vigoren** [algesten/hangupsjs#10]
Hello!

I have been playing around with your library and testing the events that need to be investigated and this is what I have found so far.

**notification_level**: Is triggered when you logged in user changes checks or unchecks the notifications option (activated once save is clicked)
```javascript
[ [ 'Convo_ID', [length]: 1 ],
  10,
  0,
  1432694425198000,
  [length]: 4,
  _header: { active_client_state: { k: 'NO_ACTIVE_CLIENT', v: 0 },
    request_trace_id: '-4970867828236569204',
    current_server_time: 1432694425198000 } ]
```

**easter_egg**: Is triggered when anyone in the conversation triggers an easter egg (eg /ponies)
```javascript
[ [ 'User_Who_Sent_ID', 'User_Who_Sent_ID', [length]: 2 ],
  [ 'Convo_ID', [length]: 1 ],
  [ 'ponies', null, 1, [length]: 3 ],
  [length]: 3,
  _header: { active_client_state: { k: 'NO_ACTIVE_CLIENT', v: 0 },
    request_trace_id: '8665677000454308538',
    current_server_time: 1432694257109000 } ]
```

**self_presence**: This seems to trigger every now and then, not sure what the values represent but here is a sample dump of it
```javascript
[ [ [ 'lcsw_hangoutsDC655C9D', '129CC29950A5EBDF', [length]: 2 ],
    40,
    [length]: 2 ],
  [length]: 1,
  _header: { active_client_state: { k: 'OTHER_CLIENT_IS_ACTIVE', v: 2 },
    request_trace_id: '-8193790167963770717',
    current_server_time: 1432694783833000 } ]
```

**presence**: Again this seems to trigger every now and then I couldn't get it to consistantly trigger but here is a dump
```javascript
[ [ [ [ '113416088583634280153', '113416088583634280153', [length]: 2 ],
      [ 1, 0, [length]: 2 ],
      [length]: 2 ],
    [length]: 1 ],
  [length]: 1,
  _header: { active_client_state: { k: 'NO_ACTIVE_CLIENT', v: 0 },
    request_trace_id: '-863313235872582273',
    current_server_time: 1432694728248000 } ]
```

I hope this is a little bit helpful

**Comment by algesten** [comment]
oh wow! thanks! i'll update the documentation right now!
