### ISSUE TITLE
broken again?

### ISSUE THREAD

**Issue by djacobow** [algesten/hangupsjs#103]
I had to restart my hangupsj-based chatbot today and it is not working.

Issue seems to be with some datastructure not existing and tripping up init.js at line 125.

Some poking around shows that this is with a data chunk that is supposed to have the account's email in it, but it just looks like this:

```
[ [ 'cin:xc', '' ] ]
```

So the function in:

```
email: {
    key: 'ds:36',
    fn: function(d) {
        return d[0][2];
    }
}
```

fails because the third element of the first element above does not exist.

I just hardcoded that function to return my account's email and it seems to work, but that is obviously not a correct solution.

**Comment by HomerSp** [comment]
Is it still working for you? Google seem to have done some server-side changes - amongst them changing the key for email to 'ds:31'. Unfortunately they seem to have also completely removed the data for conv_states, which means that no conversations at all show up for me.
Haven't found any way around this yet, but I'm hoping this was a mistake on Google's side and that they will revert it. If not, maybe the devs have some ideas?

**Comment by djacobow** [comment]
So my bot doesn't use everything that's available in hangups. It just receives messages and returns them. With the email hack, it works. Could very well be that the conversation state is broken; just not using it.
