### ISSUE TITLE
createconversation always errors

### ISSUE THREAD

**Issue by jamescarr** [algesten/hangupsjs#16]
`createconversation` always seems to error for me. Here's what I'm trying:

```javascript
      var chat_id = result.entity[0].id.chat_id;
      client.createconversation([chat_id], false).then(function(rs) {
        res.json(rs);
      }).catch(function(rs) { 
        res.json(JSON.parse(rs.body.toString()));
      });
```
A dump of chat_id reveals it is indeed populated. Here's the result:

```javascript
{
    "error": {
        "errors": [
            {
                "domain": "global",
                "reason": "parseError",
                "message": "Parse Error"
            }
        ],
        "code": 400,
        "message": "Parse Error"
    }
}

```

Any ideas?

**Comment by jamescarr** [comment]
Raw request: 

```javascript

{ authorization: 'SAPISIDHASH <censored>',
     'x-origin': 'https://talkgadget.google.com',
     'x-goog-authuser': '0',
     'Content-Type': 'application/json+protobuf' },
  body: '[[[6,3,"chat_wcs_20150528.152027_RC2","1433192105"],["lcsw_hangoutsC1DA42D3","FFA0669F682F16C2"],null,"en"],1,2408885808,null,[[["106382582559490520071",null,null,"unknown",null,[]]]]]',
  encoding: null,
  timeout: 30000 }

```

**Comment by jamescarr** [comment]
I also did a parseInt on chat_id as well in case google hangouts was strict about it being an integer.

**Comment by algesten** [comment]
wow. we just got the same error in https://github.com/yakyak/yakyak trying to use that. i fix now

**Comment by jamescarr** [comment]
Killer let me know ... or if you could provide me a hint and I'll throw some brainpower at it.

**Comment by jamescarr** [comment]
LOL... that's it. :-D

**Comment by algesten** [comment]
one too many [] in the translation from python lib. whoops. https://github.com/tdryer/hangups/blob/master/hangups/client.py#L843

**Comment by algesten** [comment]
i published 0.7.5

**Comment by jamescarr** [comment]
Thanks... works like a charm. Really digging this... it seems that gtalk shut off XMPP access unexpectedly last week.

**Comment by algesten** [comment]
oh. didn't know that. wonder if that means more people will come here for an alternative. i feel the lib is nearing a 1.0 the thing left to fix is how it handles long running sessions and network interruptions. I've started tackling it, so i believe it's getting there.
