### ISSUE TITLE
Feature Request: Ability to pass in the cookie jar store (instead of hard coding the file store)

### ISSUE THREAD

**Issue by mehcode** [algesten/hangupsjs#27]
https://github.com/algesten/hangupsjs/blob/master/src/client.coffee#L125

**Comment by algesten** [comment]
shouldn't be too hard to make a `jar` option.

**Comment by mehcode** [comment]
Awesome. I don't mind making a PR for this. Just wanted to see you felt first.

My use case is I want to be able to open up multiple connections. After the first one, all subsequent connections ignore the token I give it and use the cached session from the first connection.

**Comment by mehcode** [comment]
Well.. there you go making it while I typed that. Ha. Thanks.

**Comment by algesten** [comment]
You still need to prepare for that the session may expire, otherwise I think it should work. Never tried it. Let me know how it goes.
