### ISSUE TITLE
Feature Request: More "elegant" method of passing in an a cached access token

### ISSUE THREAD

**Issue by mehcode** [algesten/hangupsjs#28]
```js
client.connect(function() {
    return {auth: function() {
      return token
    }}
  })
```

^ The above is the only method that seems to work for sending in an access token directly. Can we make it a little nicer to look at?

```js
// Maybe
client.connect({token})

// Or
client.connect(token)
```

**Comment by algesten** [comment]
thing is. the token may expire during a session and we must ask for a new one. the intention is that the auth callback will trigger a user interaction to authenticate and generate the next token.

**Comment by mehcode** [comment]
Ah. So you're saying that the auth method would get invoked whenever the session expires? That makes sense. I just didn't understand. 

Why the outer most function then?

**Comment by algesten** [comment]
Hm. No idea. I initially ported the python project, may be I got it from there. Or may be I just was confused :)
