### ISSUE TITLE
Search Entity by email ?

### ISSUE THREAD

**Issue by rikka94** [algesten/hangupsjs#37]
Is this possible to implement ?

Need a way to accurately get a person's ID..

Thanks

**Comment by algesten** [comment]
not sure really. generally the answer to these questions are: does Google official hangouts client let you do it? if yes. you run the in-browser chat version (not plugin) and analyse the calls it makes to achieve it.

first when we know how the official client does it, can we try to implement.

**Comment by rikka94** [comment]
Yeah, i asked this question after i realized i can search by email at hangouts pages and also mobile apps.

The search panel will trigger once '@' is entered after at least a single alphabets..

But i have no idea how to analyse the call though..

**Comment by algesten** [comment]
does it work if you try the same strategy?

**Comment by rikka94** [comment]
Nope, i tried both searchentities and getentitybyid , 
searchentities return only response header.
getentitybyid return single object which is null..

I guess there are minor difference in the request params for ID vs email in getentitybyid

**Comment by rikka94** [comment]
Alright i got it to work

I changed the code below in Client.getentitybyid.
```javascript
results.push([String(chat_id)]);

To

results.push([None, None, String(chat_id)]);
```

Now the I can get the result using email.

**Comment by algesten** [comment]
great! you think we should update the documentation on that?

**Comment by rikka94** [comment]
The original one worked only for chatID and the new one worked only for email after i tested it.

I guess can separate into 2 functions or do some preprocessing inside the function to determine whether the input is email or chatID before writing to the request..

**Comment by algesten** [comment]
perhaps a getentitybyemail?

**Comment by rikka94** [comment]
great! that's actually how I modified it currently.
