### ISSUE TITLE
Get sender name

### ISSUE THREAD

**Issue by optimistiks** [algesten/hangupsjs#38]
Hey, is there a way to associate incoming message with a user, I mean to retrieve his name somehow? I know there is a sender_id, but maybe there is a way to get something more human-readable

**Comment by algesten** [comment]
yes. check out `getentitybyid`.

**Comment by optimistiks** [comment]
thanks, it worked :)

**Comment by magdawi** [comment]
i tried to use getentitybyid to get the username of the sender but instead of the user, it returns { state: 'pending' }

any solutions?

**Comment by BopItFreak** [comment]
@algesten Yeah, I'm getting the same problem: {state: 'pending'}
my code looks like this: 
var name = client.getentitybyid([ev.sender_id.chat_id])
