### ISSUE TITLE
HangupsJS consumes all memory due to brain "updating user list"

### ISSUE THREAD

**Issue by drwahl** [algesten/hangupsjs#45]
After launching the hubot with the hangupsjs adapter, the console is spammed with:

`[Tue Mar 15 2016 04:56:44 GMT+0000 (UTC)] INFO Brain Loaded...updating user list`

This is happening a lot. Something on the order of 100 or so per second.  It seems like it eventually consumes all the memory of the system (in my case, a docker container) and crashes.

Halp?

**Comment by drwahl** [comment]
Scratch that.... This is for hubot-hangupsjs, which is obviously confusing.  As you were, men!

**Comment by algesten** [comment]
:)
