### ISSUE TITLE
New lines in message builder

### ISSUE THREAD

**Issue by lorenzos** [algesten/hangupsjs#7]
It looks like, atm, there is no way to place a new line in a message. I've tried:

    .text("\n")
    .text('ciao\n')
    .text("\nciao");

But none work. I think the newline is a special segment, because that's what I see when I receive one:

	[ { type: { k: 'TEXT', v: 0 },
		text: 'first line',
		formatting: { bold: 0, italic: 0, strikethrough: 0, underline: 0 },
		link_data: null },
	  { type: { k: 'LINE_BREAK', v: 1 },
		text: '\n',
		formatting: null,
		link_data: null },
	  { type: { k: 'TEXT', v: 0 },
		text: 'second line',
		formatting: { bold: 0, italic: 0, strikethrough: 0, underline: 0 },
		link_data: null } ]

**Comment by algesten** [comment]
cool. i'll make that a builder option and perhaps also parse an incoming line to look for \r.

**Comment by algesten** [comment]
it's just a new builder method `.linebreak()` since i don't want to introduce a concept of parsing text passed by the builder user.

**Comment by lorenzos** [comment]
:wink: Great
