### ISSUE TITLE
Links not working in message builder

### ISSUE THREAD

**Issue by lorenzos** [algesten/hangupsjs#8]
I know it is written in docs (consider this issue a reminder), but do you have any idea why they not work? Can I help someway?

**Comment by algesten** [comment]
i don't get it. my only theory right now is that google somehow requires all links to go through their tracking systems rewritten by their API:s or something.

**Comment by algesten** [comment]
found it! ... it was the same as newline problem. i was sending the wrong type of message. thanks!

**Comment by lorenzos** [comment]
Thank you! :+1:

**Comment by adriankremer** [comment]
Links aren't working anymore (*for me since August 22) can someone reproduce this?

**Comment by lorenzos** [comment]
To me, they work. Here's the code I just tested, I'm at commit 6510b0e29639:

```javascript
var builder = new HangupsJS.MessageBuilder();
builder.bold(title);
builder.linebreak();
builder.link(url, url)
builder.bold("title");
builder.linebreak();
builder.text(description);

client.sendchatmessage(conversation_id, builder.toSegments(), null);
```

Why don't you share a non-working example, so I can test it?

**Comment by adriankremer** [comment]
I've tried your example without success.
It seems to be a problem with the account itself. I've tried to renew the AuthToken but the link from Readme.md is broken.
